feat: admin page
DanericNetwork/Biblio-App pull request #23
Opened 2024-01-10 14:25 UTC by DanericNetwork

2024-01-11 08:26 UTC, Timtendo12 requested changes

2024-01-11 08:26 UTC, Timtendo12 commented on src/resources/vue/pages/admin/index.vue
> +          id: "vuechart-example",
Example?

2024-01-17 10:52 UTC, Timtendo12 requested changes

2024-01-17 10:52 UTC, Timtendo12 commented on src/resources/vue/layouts/admin-layout.vue
> +      userData: {
hoe huh waht hu hheo hoe heuh huh waht heuh huh ehe huh? 
![282fe1d7e40e216c723740b0af255952](https://github.com/DanericNetwork/Biblio-App/assets/41442518/876aad1b-01c1-4bd0-b51c-d31b3679123d)

2024-01-17 10:52 UTC, Timtendo12 commented on src/resources/vue/layouts/admin-layout.vue
> +      userData: {
zie: https://inertiajs.com/pages

2024-01-17 10:52 UTC, Timtendo12 commented on src/resources/vue/layouts/admin-layout.vue
> +      userData: {
specifieker:

https://inertiajs.com/shared-data

2024-01-17 13:10 UTC, Chrinsieboy approved these changes

2024-01-17 13:40 UTC, Timtendo12 approved these changes

2024-01-17 13:41 UTC, merged