Feature/dashboard main pagina
DanericNetwork/Biblio-App pull request #31
Opened 2024-01-17 11:15 UTC by Huib8

2024-01-18 13:36 UTC, Chrinsieboy requested changes
Sorry huib maar...

2024-01-18 13:36 UTC, Chrinsieboy commented on src/app/Http/Controllers/dashboardTerminalController.php
> +<?php
File moet beginnen met Hoofdletter 🥰

2024-01-18 13:36 UTC, Chrinsieboy commented on src/app/Http/Controllers/dashboardTerminalController.php
> +class dashboardTerminalController extends Controller
~~dashboardTerminal...~~ **DashboardTerminal...**

2024-01-18 13:36 UTC, Chrinsieboy commented on src/app/Http/Controllers/dashboardTerminalController.php
> +    public function dashboard() {
dashboard to index

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/components/Tabs.vue
> +            },
wanneer er meer items zijn, doet de achtergrond het niet.

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/components/Tabs.vue
> +            },
Same voor de andere tabs

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/components/ItemCard.vue
> +    tab: Object,
andere naam dan tab gebruiken? Misschien item?

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/components/Tabs.vue
> +<template>
Deze file snap ik niks van, kan je me dit uitleggen?

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/components/icon.vue
> +      console.log(this.icon);
Log moet weg pls UwU

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/components/terminal-scan.vue
> +  created() {
Created/Log moet weg pls UwU

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/pages/index.vue
> +    <span class="terminal-title"
Op een lijn laten pls

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/pages/terminal-dashboard.vue
> +        class="Box1"
aparte classes? Waarom geen gebruik van gaps?

2024-01-18 13:36 UTC, Chrinsieboy commented on src/resources/vue/pages/terminal-dashboard.vue
> +.Box2 {
Verwijder deze class en gebruik gap in boxes, werkt beter

2024-01-18 13:36 UTC, Chrinsieboy commented on src/routes/web.php
> +Route::get('/dashboard', [dashboardTerminalController::class, 'dashboard']);
dashboardTermi... met hoofdletter en class naar index

2024-01-18 14:44 UTC, Huib8 commented on src/resources/vue/components/Tabs.vue
> +            },
fixed

2024-01-19 10:09 UTC, Timtendo12 commented on src/app/Http/Controllers/dashboardTerminalController.php
> +<?php
Ik zou de controllernaam aanpassen naar AppController.

2024-01-19 10:11 UTC, Timtendo12 commented on src/resources/vue/pages/terminal-dashboard.vue
> +    ItemCard,
Word deze ook gebruikt in deze file?

2024-01-19 10:13 UTC, Timtendo12 commented on src/resources/vue/components/Tabs.vue
> +          :tab="tab"
ipv dat je alle tabs meegeeft, Waarom geef je niet specifiek de item mee?

```js
:item="tab.items[itemIndex]"
```

Dan hoef je in de itemCard alleen maar:

`item.content`
`item.description`

etc te doen.

2024-01-19 10:17 UTC, Chrinsieboy requested changes

2024-01-19 10:17 UTC, Chrinsieboy commented on src/resources/vue/components/Tabs.vue
> +<template>
Ik weet niet waar de tabs prc zit maar je hebt nog ruimte over aan de boven en onderkant
![image](https://github.com/DanericNetwork/Biblio-App/assets/50674927/856ecdc5-5006-4ccc-a142-63aaf68359f7)

2024-01-19 10:17 UTC, Chrinsieboy commented on src/resources/vue/components/icon.vue
> +          return `bob`;
bob?

2024-01-19 10:17 UTC, Chrinsieboy commented on src/resources/vue/pages/terminal-dashboard.vue
> +    ItemCard,
Mee eens

2024-01-19 10:17 UTC, Chrinsieboy commented on src/routes/web.php
> +use App\Http\Controllers\dashboardTerminalController;
Hoofdletter `DashboardTerminalController`

2024-01-19 10:17 UTC, Chrinsieboy commented on src/app/Http/Controllers/dashboardTerminalController.php
> +<?php
Mee eens

2024-01-22 10:02 UTC, Timtendo12 requested changes

2024-01-22 10:02 UTC, Timtendo12 commented on src/app/Http/Controllers/AppController.php
> +        return Inertia::render('terminal-dashboard');
Miss de page verplaatsen naar -> /pages/teminal/index.vue. Kunnen we zometeen alle pagina's van de terminal in zn eigen mapje plaatsten.

2024-01-22 10:02 UTC, Timtendo12 commented on src/resources/vue/components/Tabs.vue
> +          items: [
Mock data weghalen.

2024-01-22 10:51 UTC, Huib8 commented on src/resources/vue/components/Tabs.vue
> +          items: [
eenmaal weg doen als echte data word toegevoegd

2024-01-22 11:55 UTC, Timtendo12 approved these changes

2024-01-22 12:20 UTC, Huib8 commented
![afbeelding](https://github.com/DanericNetwork/Biblio-App/assets/127506920/1cf7b2ac-2a42-4f6b-87e7-6d32cde32afa)


![afbeelding](https://github.com/DanericNetwork/Biblio-App/assets/127506920/2a774ed1-89b6-4339-850c-847ffe33e8ee)

2024-01-22 12:30 UTC, Chrinsieboy requested changes

2024-01-22 12:30 UTC, Chrinsieboy commented on src/resources/vue/components/ItemCard.vue
> +        <p>{{ item.content }}</p>
item.title?

2024-01-22 12:30 UTC, Chrinsieboy commented on src/resources/vue/components/Tabs.vue
> +<template>
Kleuren en fonts van de tabs komen niet echt overeen

2024-01-22 12:30 UTC, Chrinsieboy commented on src/routes/web.php
> +Route::get('/dashboard', [AppController::class, 'index']);
veranderen naar terminal

2024-01-22 12:37 UTC, Huib8 commented on src/resources/vue/components/Tabs.vue
> +<template>
changes fixed

2024-01-22 13:26 UTC, Chrinsieboy requested changes

2024-01-22 13:26 UTC, Chrinsieboy commented on src/resources/vue/pages/terminal/index.vue
> +<template>
Ik weet niet in waar je de height hebt aangepast maar de indexpage is nu fricked

2024-01-22 13:26 UTC, Chrinsieboy commented on src/resources/vue/components/Tabs.vue
> +<template>
Laatste dingetje voor Tabs (hoop ik)
Zorg er voor dat de tabs geen rounded corners heeft :)

2024-01-22 13:26 UTC, Chrinsieboy requested changes

2024-01-22 13:26 UTC, Chrinsieboy commented on src/resources/vue/pages/terminal/index.vue
> +<template>
En pas de scrollbar aan naar een mooi kleurtje :D

2024-01-22 14:46 UTC, Chrinsieboy approved these changes

2024-01-24 08:44 UTC, Timtendo12 submitted a review, later dismissed
👍🏻

2024-01-24 08:58 UTC, Timtendo12 approved these changes

2024-01-24 09:00 UTC, Chrinsieboy approved these changes
🚀

2024-01-24 09:00 UTC, Timtendo12 approved these changes

2024-01-24 09:00 UTC, merged